extends StateAnimatedActor

export (NodePath) var fall_node
export (NodePath) var move_node

onready var fall_state: State = get_node(fall_node)
onready var move_state: State = get_node(move_node)

func enter() -> void:
	.enter()
#	parent.set_hurtbox(true)
	move_component.velocity.x = 0
	if debug_state:
		print(owner.name, " Move Component: ", move_component.desired_movement_vector.x)

func process_physics(delta: float) -> State:

#	parent.velocity.y += gravity * delta
#	#parent.velocity = parent.move_and_slide(parent.velocity, Vector2(0, -1))
#	parent.velocity.x = move_component.desired_movement_vector.x * move_speed
#	parent.velocity = parent.move_and_slide(parent.velocity, Vector2(0, -1))
	
	move_actor_as_desired(delta)
	
	if move_component.velocity.x != 0.0:
		return move_state
	
	if !parent.is_on_floor():
		return fall_state
	return null
