extends State

export (NodePath) var jump_node
export (NodePath) var fall_node
#export (NodePath) var move_node
export (NodePath) var fire_node
export (NodePath) var wander_node
export (NodePath) var attack_node

onready var jump_state: State = get_node(jump_node)
onready var fall_state: State = get_node(fall_node)
#onready var move_state: State = get_node(move_node)
onready var fire_state: State = get_node(fire_node)
onready var wander_state: State = get_node(wander_node)
onready var attack_state: State = get_node(attack_node)

func enter(state_modifiers: Array = []) -> void:
	.enter()
	parent.set_hurtbox(true)
	parent.velocity.x = 0
	state_timeout.start()

func process_frame(_delta: float) -> State:

	if state_timeout.time_left == 0:
		return wander_state
		
	if parent.player_detection.is_colliding():
		return attack_state

#	if get_jump() and parent.is_on_floor():
#		return jump_state
#
#	if move_component.wants_jump() and parent.is_on_floor():
#		return jump_state
##	if move_component.get_movement_direction() != 0.0:
##		return move_state
#	if move_component.wants_shoot():
#		return fire_state
#
##	move_component.wants_jump() 
#	move_component.get_movement_direction()

#	if Input.is_action_just_pressed('dash'):
#		return dash_state
	return null

func process_physics(delta: float) -> State:
	parent.velocity.y += gravity * delta
	#parent.velocity = parent.move_and_slide(parent.velocity, Vector2(0, -1))
	
	if !parent.is_on_floor():
		return fall_state
	return null
