extends StateAnimatedActor

export (NodePath) var move_node

onready var move_state: State = get_node(move_node)

func enter() -> void:
	.enter()
#	parent.set_hurtbox(true)
	if debug_state:
		print(owner.name, " Move Component: ", move_component.desired_movement_vector.x)
	state_timeout.start()

func process_frame(delta):
	if state_timeout.time_left == 0:
		return move_state
	return null

func process_physics(delta: float) -> State:

#	parent.velocity.y += gravity * delta
#	#parent.velocity = parent.move_and_slide(parent.velocity, Vector2(0, -1))
#	parent.velocity.x = move_component.desired_movement_vector.x * move_speed
#	parent.velocity = parent.move_and_slide(parent.velocity, Vector2(0, -1))
	
	return null
