extends Node

## This singleton sits in the middle allowing multiple game areas to call and
# manipulate the UI

enum UI_PANES {OFF, HUD, DIALOG}

var dialog_text = 'foo'
var dialog_portrait = preload("res://icon.png")
var current_pane = UI_PANES.OFF

var debug_text :String

# Declare member variables here. Examples:
# var a = 2
# var b = "text"


# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass
