extends StateAnimatedActor

export (NodePath) var fall_node
export (NodePath) var idle_node

onready var fall_state: State = get_node(fall_node)
onready var idle_state: State = get_node(idle_node)

func process_physics(delta: float) -> State:

	move_actor_as_desired(delta)
		
	if move_component.velocity.x == 0.0:
		return idle_state

	#Flip the character before tha actual move maybe.
	parent.transform.x.x = move_component.get_movement_direction()
	
	if !parent.is_on_floor():
		return fall_state
	return null
